name: Generate Daily Devotional

on:
  schedule:
    - cron: '0 9 * * *' # Runs at 9:00 AM UTC (4:00 AM EST)
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write # Grant write permissions to the GITHUB_TOKEN

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.1' # Specify a valid Ruby version
          bundler-cache: true

      - name: Install Dependencies
        run: bundle install

      - name: Generate Devotional
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: bundle exec ruby scripts/generate_devotional.rb

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          # Check if there are changes to commit
          if ! git diff-index --quiet HEAD; then
            git commit -m "Automated devotional for $(date +'%Y-%m-%d')"
            git push
          else
            echo "No changes to commit."
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
